"""
filters/solo_motif.py
=====================
Restrict sum-of-bits scoring to a single, user-specified motif.

Usage
-----
    from filters.solo_motif import filter_by_motif_name

    allowed = filter_by_motif_name("10-GCUGGAGCUGGGRU")
    stable_raw = read_best_site(stable_path, allowed_motifs=allowed)

The motif name must match exactly what appears in column 3 of the narrowPeak
file (e.g. "10-GCUGGAGCUGGGRU"). These names are generated by STREME/FIMO
as a number prefix followed by the consensus sequence.

The function returns a one-element set, which is consistent with what the
streme_filters functions return — so all filters can be combined using set
intersection if you ever want to apply multiple filters at once:

    combined = filter_by_evalue(xml, 0.05) & filter_by_motif_name("10-GCUGGAGCUGGGRU")
"""

import sys


def filter_by_motif_name(motif_name):
    """
    Return an allowed-motifs set containing only the specified motif.

    Parameters
    ----------
    motif_name : str
        The exact motif name as it appears in narrowPeak column 3,
        e.g. "10-GCUGGAGCUGGGRU".

    Returns
    -------
    allowed : set[str]
        A one-element set. Pass to read_best_site(allowed_motifs=).
    """
    if not isinstance(motif_name, str) or not motif_name.strip():
        sys.exit(
            "ERROR: filter_by_motif_name requires a non-empty string. "
            f"Got: {motif_name!r}"
        )

    allowed = {motif_name.strip()}
    print(f"  Solo-motif filter: scoring only '{motif_name}'")
    return allowed
